/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:261: UserWarning: Attribute 'model' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model'])`.
  rank_zero_warn(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████| 2/2 [00:00<00:00, 26.67it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
  | Name  | Type   | Params
---------------------------------
0 | model | ResNet | 11.2 M
---------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.720    Total estimated model params size (MB)
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:487: PossibleUserWarning: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test/predict dataloaders.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('dim:', ...)` in your `validation_step` but the value needs to be floating point. Converting it to torch.float32.

Epoch 0:   9%|███▊                                     | 85/927 [00:01<00:18, 45.86it/s, loss=2.07, v_num=zm5z]
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.






Epoch 0:  88%|███████████████████████████████████     | 814/927 [00:15<00:02, 51.72it/s, loss=1.55, v_num=zm5z]








Epoch 1:  93%|█████████████████████████████████████▏  | 861/927 [00:16<00:01, 53.36it/s, loss=1.39, v_num=zm5z]







Epoch 2:  80%|████████████████████████████████▏       | 746/927 [00:14<00:03, 50.67it/s, loss=1.19, v_num=zm5z]








Epoch 3:  91%|████████████████████████████████████▎   | 841/927 [00:15<00:01, 53.03it/s, loss=1.09, v_num=zm5z]








Epoch 4:  95%|█████████████████████████████████████▏ | 883/927 [00:16<00:00, 53.54it/s, loss=0.996, v_num=zm5z]







Epoch 5:  81%|███████████████████████████████▍       | 747/927 [00:14<00:03, 49.98it/s, loss=0.828, v_num=zm5z]








Epoch 6:  85%|█████████████████████████████████▏     | 789/927 [00:15<00:02, 51.31it/s, loss=0.691, v_num=zm5z]








Epoch 7:  90%|███████████████████████████████████▏   | 835/927 [00:15<00:01, 52.52it/s, loss=0.627, v_num=zm5z]








Epoch 8:  96%|█████████████████████████████████████▎ | 886/927 [00:16<00:00, 53.76it/s, loss=0.538, v_num=zm5z]







Epoch 9:  81%|███████████████████████████████▋       | 754/927 [00:14<00:03, 50.41it/s, loss=0.401, v_num=zm5z]

Validation DataLoader 0:  97%|█████████████████████████████████████████████▋ | 180/185 [00:02<00:00, 81.32it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/media/data/chitb/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('test accuracy: ', ...)` in your `test_step` but the value needs to be floating point. Converting it to torch.float32.









Testing DataLoader 0: 100%|███████████████████████████████████████████████| 7178/7178 [00:19<00:00, 374.33it/s]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
     test accuracy:         0.5319030284881592
